### ISSUE TITLE
redfishProfileSimulator error?

### ISSUE THREAD

**Issue by jimlundberg** [DMTF/Redfish-Profile-Simulator#27]
Tried changing the BootOverride:

redfishtool -r 127.0.0.1:5000 -u root -p password123456 -S Never Systems --all setBootOverride Disabled Once
   redfishtool: Transport: Response Error: status_code: 500 -- Internal Server Error

But the RedfishProfileSimulator gave an error saying it can not find root.systems

127.0.0.1 - - [19/Jul/2022 18:03:43] "GET /redfish/v1/Systems/2M220100SL/ HTTP/1.1" 200 -
in rfAuthRequired
headers: Host: 127.0.0.1:5000
Accept-Encoding: identity
User-Agent: python-requests/2.27.1
Accept: application/json
Connection: keep-alive
Odata-Version: 4.0
Content-Type: application/json
Content-Length: 51
Authorization: Basic cm9vdDpwYXNzd29yZDEyMzQ1Ng==

rdata:{'Boot': {'BootSourceOverrideEnabled': 'Disabled'}}
[2022-07-19 18:03:43,830] ERROR in app: Exception on /redfish/v1/Systems/2M220100SL/ [PATCH]
Traceback (most recent call last):
  File "/gsa/yktgsa-h3/13/jimlund/venv/lib64/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/gsa/yktgsa-h3/13/jimlund/venv/lib64/python3.6/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/gsa/yktgsa-h3/13/jimlund/venv/lib64/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/gsa/yktgsa-h3/13/jimlund/venv/lib64/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/gsa/yktgsa-h3/13/jimlund/redfish/Redfish-Profile-Simulator/v1sim/flask_redfish_auth.py", line 139, in decorated
    return (f(*args, **kwargs))
  File "/gsa/yktgsa-h3/13/jimlund/redfish/Redfish-Profile-Simulator/v1sim/redfishURIs.py", line 86, in rf_computer_systempatch
    obj = patch_path(root.systems, sys_path)
AttributeError: 'RfServiceRoot' object has no attribute 'systems'
127.0.0.1 - - [19/Jul/2022 18:03:43] "PATCH /redfish/v1/Systems/2M220100SL/ HTTP/1.1" 500 -

**Comment by mraineri** [comment]
Closing; will not be fixing since this tool has been deprecated for other mockup tools/simulators.
